# Measures of effect (association) {#sec-measure-of-effect}




## Risk Ratios

### Excercise 1

You are part of a research team conducting a cohort study to evaluate the effect of hormone replacement therapy (HRT) on the development of coronary heart disease (CHD). The research team enrolled post-menopausal women on HRT with no prior history of CHD and followed them for 7 years. 
<p style="font-size: 16px; color: gray;"> Sssume no loss to follow-up.</p>



<p style="font-size: 16px; color: gray; font-weight: 100;font-style: italic;">Remember: Exposure, HRT, is on the left side of the table, while the outcome, CHD, is on the top of the table.</p>

```{=html}
<table cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%;">
  <tr style="width:10%; font-weight:900;">
    <th style="background: #38A3A5; color: white;width: 25%;"></th>
    <th style="background: #38A3A5; color: white;">CHD (+)</th>
    <th style="background: #38A3A5; color: white;">CHD (-)</th>
    <th style="background: #38A3A5; color: white;">Total</th>
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white; font-weight:900;"">HRT (+)</th>
    <td>210</td>  <!-- Replace with actual data -->
    <td>3290</td>  <!-- Replace with actual data -->
    <td>3500</td>  <!-- Row total -->
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white; font-weight:900;"">HRT(-)</th>
    <td>250</td>  <!-- Replace with actual data -->
    <td>6250</td>  <!-- Replace with actual data -->
    <td>6500</td>  <!-- Row total -->
  </tr>
  <tr>
    <th style="background: #38A3A5; color: white;width: 25%;font-weight:900;"">Total</th>
    <td>460</td>  <!-- Column total -->
    <td>9540</td>  <!-- Column total -->
    <td>10000</td> <!-- Grand total -->
  </tr>
</table>
```

_Task:_

<ul style="list-style-type: upper-alpha;">
<li>Calculate and interpret the relative risk (RR) for the cohort.</li>

<details><summary>Results</summary>

$$
P(D+ \mid E+)= \frac{210}{3500} = 0.060
$$

$$
P(D+ \mid E-)= \frac{250}{6500} = 0.038
$$ 

$$
RR= \frac{0.64}{0.4} = 1.58
$$ 


__Interpretation:__ Women on HRT have 1.58 times the risk of CHD compared to those who do not take HRT over 7 years.

</details>

<li>Calculate and interpret the risk difference (RD) for the cohort</li>

<details><summary>Results</summary>

$$
RD= 0.060 - 0.038 = 0.022
$$

__Interpretation:__ There is an excess of 22 cases of CHD per 1000 women attributable to HRT use over 7 years.


</details>

</ul>

### Excercise 2

A study assesses the relationship between smoking habits and esophageal cancer. 1200 people were enrolled in the study. 450 out of 1200 participants had esophageal cancer, while 320 of the diseased participants were smokers while. The total number of smokers in the study was 550.

<p style="color: #a50e58; font-weight: 900;">Fill out the 2x2 table! </p>

```{=html}
<table cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; ">
  <tr style="width:10%; font-weight:900;">
    <th style="background: #38A3A5; color: white;width: 25%;"></th>
    <th style="background: #38A3A5; color: white;">Lung Cancer  (+)</th>
    <th style="background: #38A3A5; color: white;">Lung Cancer  (-)</th>
    <th style="background: #38A3A5; color: white;">Total</th>
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white; font-weight:900;">Smoker (+)</th>
    <td></td>  <!-- Replace with actual data -->
    <td></td>  <!-- Replace with actual data -->
    <td></td>  <!-- Row total -->
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white; font-weight:900;">Smoker(-)</th>
    <td></td>  <!-- Replace with actual data -->
    <td></td>  <!-- Replace with actual data -->
    <td></td>  <!-- Row total -->
  </tr>
  <tr>
    <th style="background: #38A3A5; color: white;width: 25%; font-weight:900;">Total</th>
    <td></td>  <!-- Column total -->
    <td></td>  <!-- Column total -->
    <td></td> <!-- Grand total -->
  </tr>
</table>
```

<details><summary>Results</summary>

```{=html}
<table cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; ">
  <tr style="width:10%; font-weight:900;">
    <th style="background: #38A3A5; color: white;width: 25%;"></th>
    <th style="background: #38A3A5; color: white;">Lung Cancer  (+)</th>
    <th style="background: #38A3A5; color: white;">Lung Cancer  (-)</th>
    <th style="background: #38A3A5; color: white;">Total</th>
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white; font-weight:900;">Smoker (+)</th>
    <td>320</td>  <!-- Replace with actual data -->
    <td>230</td>  <!-- Replace with actual data -->
    <td>550</td>  <!-- Row total -->
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white; font-weight:900;">Smoker(-)</th>
    <td>130</td>  <!-- Replace with actual data -->
    <td>520</td>  <!-- Replace with actual data -->
    <td>650</td>  <!-- Row total -->
  </tr>
  <tr>
    <th style="background: #38A3A5; color: white;width: 25%; font-weight:900;">Total</th>
    <td>450</td>  <!-- Column total -->
    <td>750</td>  <!-- Column total -->
    <td>1200</td> <!-- Grand total -->
  </tr>
</table>
```

</details>

_Task:_

<ul style="list-style-type: upper-alpha;">
<li> What proportion of the incidence of esophageal cancer can be directly attributed to smoking?</li>
<details><summary>Results</summary>

$$
\text{Atributable Risk} = \frac{320}{550} - \frac{130}{650} =  0.58 – 0.20 = 0.38
$$

__Interpretation:__ 0.38 or 38% of the cases of esophageal cancer in the cohort can be attributed to smoking
</details>

<li>Calculate the risk ratio for the relationship between smoking and lung cancer, interpret the result.</li>
<details><summary>Results</summary>

$$
RR = \frac{\frac{320}{550}}{\frac{130}{650}} = \frac{0.58}{0.20} = 2.90
$$

__Interpretation:__ The risk of esophageal cancer among the smokers is 2,90 times as high as the risk of  esophageal cancer among the non-smokers.

</details>
</ul>


### Excercise 3

Coming back the investigation of the effect of HRT in post-menopausal women, you now have the following information

```{=html}
<table cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; ">
  <tr style="width:10%;font-weight:900;">
    <th style="background: #38A3A5; color: white;width: 25%;"></th>
    <th style="background: #38A3A5; color: white;">With CHD  (+)</th>
    <th style="background: #38A3A5; color: white;">Person-Years of Disease-free Follow-up</th>
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white;font-weight:900;">HRT (+)</th>
    <td>28</td>  <!-- Replace with actual data -->
    <td>52,106</td>  <!-- Replace with actual data -->
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white; font-weight:900;">HRT (-)</th>
    <td>58</td>  <!-- Replace with actual data -->
    <td>50,238</td>  <!-- Replace with actual data -->
  </tr>
</table>

```


_Task:_

<ul style="list-style-type: upper-alpha;">
<li> Calculate the Incidece rate among the exposed and unexposed women</li>
<details><summary>Results</summary>

$$
IR_{exposed}= \frac{28}{52,106} = 0.0005373661 \times 100,000 =  53.74 \text{ person-years}
$$

$$
IR_{unexposed}= \frac{58}{50,238} = 0.001154505 \times 100,000 = 115.45 \text{ person-years}
$$

</details>

<li>Calculate the rate ratio for the relationship between HRT and CHD, interpret the result.</li>


<details><summary>Results</summary>

$$
\text{Rate Ratio}= \frac{53.74}{115.45}  = 0.465
$$


__Interpretation:__ Women on HRT had 0.47 times the rate of CHD compared to women who did not use HRT

<!---
(Rate ratios are often interpreted as if they were risk ratios, e.g., post-menopausal women using HRT had 0.47 times the risk of CAD compared to women not using HRT, but it is more precise to refer to the ratio of rates rather than risk.)
-->
</details>
</ul>



## Odds Ratios

### Excercise 1

The influence of increased alcohol consumption on the incidence of esophageal cancer was retrospectively investigated in a clinic over a period of 5 years. Patients with other internal diseases were used as a comparison group.

```{=html}
<table cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; ">
  <tr style="width:10%;font-weight:900;">
    <th style="background: #38A3A5; color: white;width: 25%;"></th>
    <th style="background: #38A3A5; color: white;">Cancer (+)</th>
    <th style="background: #38A3A5; color: white;">Cancer (-)</th>
    <th style="background: #38A3A5; color: white;">Total</th>
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white;font-weight:900;">Alcohol (+)</th>
    <td>192</td>  <!-- Replace with actual data -->
    <td>54</td>  <!-- Replace with actual data -->
    <td>246</td>  <!-- Row total -->
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white;font-weight:900;">Alcohol(-)</th>
    <td>208</td>  <!-- Replace with actual data -->
    <td>333</td>  <!-- Replace with actual data -->
    <td>541</td>  <!-- Row total -->
  </tr>
  <tr>
    <th style="background: #38A3A5; color: white;width: 25%;font-weight:900;">Total</th>
    <td>400</td>  <!-- Column total -->
    <td>387</td>  <!-- Column total -->
    <td>787</td> <!-- Grand total -->
  </tr>
</table>
```



_Task:_

<ul style="list-style-type: upper-alpha;">
<li>Calculate the odds to be exposed while diseased/not diseased (i.e. case/control)</li>

<details><summary>Results</summary>

$$
Odds_{case} = \frac{192}{208} = 0.92
$$

$$
Odds_{control} = \frac{54}{333} = 0.16
$$ 

</details>
<li>Calculate and interpret the odds ratio for the occurrence of esophageal cancer</li>
<details><summary>Results</summary>

$$
OR = \frac{0.92}{0.16} = 5.75
$$

__Interpretation:__ 

- The odds of being exposed to increased alcohol consumption among cases (patients with cancer) is 5.75 times as high compared to the controls (patients with other internal diseases).

- The odds of having cancer are 5.75 times higher among individuals with increased alcohol consumption compared to those without increased alcohol consumption.

</details>

</ul>

### Excercise 2

A cohort study is investigating the impact of regular physical activity on the incidence of heart disease A total of 1500 individuals were enrolled. The prevalence of heart disease was 25%. 560 of the total participants were in the active group (those practicing physical activity). Among that group, 200 developed heart disease.


<p style="color: #a50e58; font-weight: 900;">Fill out the 2x2 table! </p>

```{=html}
<table cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; ">
  <tr style="width:10%;font-weight:900;">
    <th style="background: #38A3A5; color: white;width: 25%;"></th>
    <th style="background: #38A3A5; color: white;">Phy. Activity (+)</th>
    <th style="background: #38A3A5; color: white;">Phy. Activity (-)</th>
    <th style="background: #38A3A5; color: white;">Total</th>
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white; font-weight:900;">Smoker (+)</th>
    <td></td>  <!-- Replace with actual data -->
    <td></td>  <!-- Replace with actual data -->
    <td></td>  <!-- Row total -->
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white; font-weight:900;">Smoker(-)</th>
    <td></td>  <!-- Replace with actual data -->
    <td></td>  <!-- Replace with actual data -->
    <td></td>  <!-- Row total -->
  </tr>
  <tr>
    <th style="background: #38A3A5; color: white;width: 25%; font-weight:900;">Total</th>
    <td></td>  <!-- Column total -->
    <td></td>  <!-- Column total -->
    <td></td> <!-- Grand total -->
  </tr>
</table>
```

<details><summary>Results</summary>

```{=html}
<table cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; ">
  <tr style="width:10%;font-weight:900;">
    <th style="background: #38A3A5; color: white;width: 25%;"></th>
    <th style="background: #38A3A5; color: white;">Phy. Activity  (+)</th>
    <th style="background: #38A3A5; color: white;">Phy. Activity  (-)</th>
    <th style="background: #38A3A5; color: white;">Total</th>
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white; font-weight:900;">Smoker (+)</th>
    <td>200</td>  <!-- Replace with actual data -->
    <td>360</td>  <!-- Replace with actual data -->
    <td>560</td>  <!-- Row total -->
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white; font-weight:900;">Smoker(-)</th>
    <td>175</td>  <!-- Replace with actual data -->
    <td>765</td>  <!-- Replace with actual data -->
    <td>940</td>  <!-- Row total -->
  </tr>
  <tr>
    <th style="background: #38A3A5; color: white;width: 25%; font-weight:900;">Total</th>
    <td>560</td>  <!-- Column total -->
    <td>940</td>  <!-- Column total -->
    <td>1500</td> <!-- Grand total -->
  </tr>
</table>
```

</details>

_Task:_

<ul style="list-style-type: upper-alpha;">
<li>Calculate the risk for each group and the relative risk based on the table you filled out, interpret the results.</li>
<details><summary>Results</summary>

$$
Risk_{exposed} = \frac{200}{560} = 0.36
$$

$$
Risk_{unexposed} = \frac{175}{940} = 0.19
$$ 

$$
RR = \frac{0.33}{0.12} = 1.89
$$ 

__Interpretation:__ The risk of suffering from heart disease when practicing  physical activity is 1.89 times as high compared to participants who didn’t practice physical activity

</details>

<li>Moving to the case-control setting, assume a case-control study instead of a cohort study. Using the same previous figures. Calculate the odds and odds ratio. Please interpret your results.</li>
<details><summary>Results</summary>

$$
Odds_{case} = \frac{200}{175} = 1.14
$$

$$
Odds_{control} = \frac{360}{765} = 0.47
$$ 

$$
OR = \frac{1.67}{0.45} = 2.42
$$ 

__Interpretation:__ The odds of practicing physical activity among cases is 2.42 times as high as the odd of practicing physical activity among the controls.


</details>

</ul>

### Excercise 3

A second study is again investigating the influence of smoking on respiratory complaints. This time, 900 study participants were enrolled, 93% of those didn’t suffer from respiratory complaints. 5% of the 600 participants that were smokers suffered from respiratory complaints.

<p style="color: #a50e58; font-weight: 900;">Fill out the 2x2 table! </p>

```{=html}
<table cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; ">
  <tr style="width:10%;">
    <th style="background: #38A3A5; color: white;width: 25%;"></th>
    <th style="background: #38A3A5; color: white;">Resp. Complaints  (+)</th>
    <th style="background: #38A3A5; color: white;">Resp. Complaints  (-)</th>
    <th style="background: #38A3A5; color: white;">Total</th>
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white;">Smoker (+)</th>
    <td></td>  <!-- Replace with actual data -->
    <td></td>  <!-- Replace with actual data -->
    <td></td>  <!-- Row total -->
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white;">Smoker(-)</th>
    <td></td>  <!-- Replace with actual data -->
    <td></td>  <!-- Replace with actual data -->
    <td></td>  <!-- Row total -->
  </tr>
  <tr>
    <th style="background: #38A3A5; color: white;width: 25%;">Total</th>
    <td></td>  <!-- Column total -->
    <td></td>  <!-- Column total -->
    <td></td> <!-- Grand total -->
  </tr>
</table>
```

<details><summary>Results</summary>

```{=html}
<table cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; ">
  <tr style="width:10%;">
    <th style="background: #38A3A5; color: white;width: 25%;"></th>
    <th style="background: #38A3A5; color: white;">Resp. Complaints  (+)</th>
    <th style="background: #38A3A5; color: white;">Resp. Complaints  (-)</th>
    <th style="background: #38A3A5; color: white;">Total</th>
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white;">Smoker (+)</th>
    <td>30</td>  <!-- Replace with actual data -->
    <td>570</td>  <!-- Replace with actual data -->
    <td>600</td>  <!-- Row total -->
  </tr>
  <tr>
    <th style="width:25%; background: #38A3A5; color: white;">Smoker(-)</th>
    <td>33</td>  <!-- Replace with actual data -->
    <td>267</td>  <!-- Replace with actual data -->
    <td>300</td>  <!-- Row total -->
  </tr>
  <tr>
    <th style="background: #38A3A5; color: white;width: 25%;">Total</th>
    <td>63</td>  <!-- Column total -->
    <td>837</td>  <!-- Column total -->
    <td>900</td> <!-- Grand total -->
  </tr>
</table>
```
</details>

_Task:_

<ul style="list-style-type: upper-alpha;">
<li>Calculate the risk ratio and the odds ratio</li>
<details><summary>Results</summary>

$$
RR = \frac{\frac{30}{600}}{\frac{33}{300}} = 0.45
$$

$$
OR = \frac{\frac{30}{570}}{\frac{33}{267}} = 0.43
$$ 

</details>
<li>Looking at the different measures you calculated, explain why the RR and OR are different/similar from each other in task 2 vs. task 3.</li>

<details><summary>Results</summary>

__Rare disease assumption:__ when studying diseases that have a low prevalence (<10% as a rule of thumb) in the study population, the odds ratio is a good approximation of the risk ratio.

</details>

</ul>